# Generated by Django 5.1.5 on 2025-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativado',
            name='isento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ativado',
            name='taxa',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
