# Generated by Django 5.1.5 on 2025-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ativado_isento_ativado_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='desativado',
            name='equipamento_retirado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3),
        ),
    ]
