# Generated by Django 5.1.5 on 2025-02-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_desativado_equipamento_retirado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativado',
            name='empresa',
            field=models.CharField(default='Selecionar', max_length=252),
        ),
        migrations.AddField(
            model_name='ativado',
            name='tecnologia',
            field=models.CharField(choices=[('', 'Selecionar'), ('honest', 'Honest'), ('solunet', 'Solunet')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='desativado',
            name='motivo',
            field=models.TextField(default=False),
        ),
    ]
