# Generated by Django 5.1.5 on 2025-02-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ativado_empresa_alter_ativado_tecnologia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desativado',
            old_name='data',
            new_name='data_desativacao',
        ),
    ]
