# Generated by Django 5.1.5 on 2025-02-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_data_desativado_data_desativacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativado',
            name='empresa',
            field=models.CharField(choices=[('', 'Selecionar'), ('Honest', 'honest'), ('Solunet', 'solunet')], default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='ativado',
            name='tecnologia',
            field=models.CharField(choices=[('', 'Selecionar'), ('Rádio', 'radio'), ('Fibra', 'fibra')], default='', max_length=100),
        ),
    ]
