# Generated by Django 5.1.5 on 2025-02-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ativado_empresa_alter_ativado_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativado',
            name='empresa',
            field=models.CharField(choices=[('', 'Selecionar'), ('honest', 'Honest'), ('solunet', 'Solunet')], default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='ativado',
            name='tecnologia',
            field=models.CharField(choices=[('', 'Selecionar'), ('radio', 'Rádio'), ('fibra', 'Fibra')], default='', max_length=100),
        ),
    ]
