# Generated by Django 5.1.5 on 2025-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ativado_empresa_alter_ativado_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativado',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
    ]
