# Generated by Django 5.1.5 on 2025-03-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ativado_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='desativado',
            name='ativado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desativacao', to='app.ativado'),
        ),
        migrations.AlterField(
            model_name='desativado',
            name='motivo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='desativado',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
