# Generated by Django 5.1.5 on 2025-03-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ativado_ativo_alter_desativado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativado',
            name='sobrenome',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='ativado',
            constraint=models.UniqueConstraint(fields=('nome', 'sobrenome'), name='unique_nome_sobrenome', violation_error_message='Já existe um cliente com esta combinação de nome e sobrenome'),
        ),
    ]
