# Generated by Django 5.1.5 on 2025-04-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_ativado_sobrenome_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ativado',
            name='unique_nome_sobrenome',
        ),
        migrations.AlterUniqueTogether(
            name='ativado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ativado',
            name='empresa',
            field=models.CharField(choices=[('honest', 'Honest'), ('solunet', 'Solunet')], default='honest', max_length=252),
        ),
        migrations.AlterField(
            model_name='ativado',
            name='tecnologia',
            field=models.CharField(choices=[('radio', 'Rádio'), ('fibra', 'Fibra')], default='radio', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='ativado',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('nome', 'sobrenome'), name='unique_nome_sobrenome', violation_error_message='Já existe um cliente ativo com esta combinação de nome e sobrenome'),
        ),
    ]
